## Purpose

Purpose of the notebook is to deep dive into multiclass classification of SVM. Aim is to visualise one vs. one and one vs. rest algorithms in the 3D space.

### One vs. One

Mode11        |  Model2 |  Model3
:-------------------------:|:-------------------------:|:-------------------------:
![mdl1](./img/ovo1.png)|![mdl2](./img/ovo2.png)|![mdl3](./img/ovo3.png)

### One vs. Rest

Mode11        |  Model2 |  Model3
:-------------------------:|:-------------------------:|:-------------------------:
![mdl1](./img/ovr1.png)|![mdl2](./img/ovr2.png)|![mdl3](./img/ovr3.png)

#### Imports

In [10]:
from mpl_toolkits import mplot3d
from ipywidgets import interact
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm, datasets

#### Functions

In [11]:
def make_meshgrid(x, y, h=.02):
    """Create a mesh of points to plot in

    Parameters
    ----------
    x: data to base x-axis meshgrid on
    y: data to base y-axis meshgrid on
    h: stepsize for meshgrid, optional

    Returns
    -------
    xx, yy : ndarray
    """
    x_min, x_max = x.min() - 1, x.max() + 1
    y_min, y_max = y.min() - 1, y.max() + 1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                         np.arange(y_min, y_max, h)
                             )
    return xx, yy

#### Load Data

In [12]:
# import some data to play with
iris = datasets.load_iris()
# Take the first three features. 
X = iris.data[:, :3]
y = iris.target

# we create an instance of SVM and fit out data. We do not scale our
# data since we want to plot the support vectors
C = 1.0  # SVM regularization parameter
# models = (svm.SVC(kernel='linear', C=C),
#           svm.LinearSVC(C=C, max_iter=10000),
#           svm.SVC(kernel='rbf', gamma=0.7, C=C),
#           svm.SVC(kernel='poly', degree=3, gamma='auto', C=C))
# models = (clf.fit(X, y) for clf in models)

# title for the plots
titles = ('SVC with linear kernel',
          'LinearSVC (linear kernel)',
          'SVC with RBF kernel',
          'SVC with polynomial (degree 3) kernel')


X0, X1, X2 = X[:, 0], X[:, 1], X[:, 2]
xx, yy = make_meshgrid(X0, X1)

clf = svm.SVC(kernel='linear', C=C)
# clf = svm.LinearSVC(C=C, max_iter=10000)
clf.fit(X, y)

print(clf.intercept_.shape)
print(clf.coef_)

z0 = lambda x,y: (-clf.intercept_[0]-clf.coef_[0][0]*x-clf.coef_[0][1]*y) / clf.coef_[0][2]
z1 = lambda x,y: (-clf.intercept_[1]-clf.coef_[1][0]*x-clf.coef_[1][1]*y) / clf.coef_[1][2]
z2 = lambda x,y: (-clf.intercept_[2]-clf.coef_[2][0]*x-clf.coef_[2][1]*y) / clf.coef_[2][2]


(3,)
[[-0.30488777  0.71125336 -1.15277433]
 [-0.02638523  0.23746706 -0.68601595]
 [ 0.56787236  0.63516669 -3.43616864]]


In [13]:
clf


SVC(kernel='linear')

### Visualize SVC one_vs_one classification

#### Plot model1

In [20]:


%matplotlib inline

def plot_3D_z0(elev=30, azim=30):
    ax = plt.subplot(projection='3d')
    ax.scatter3D(X0, X1, X2, c=y, s=50, cmap='spring')
    ax.plot_surface(xx, yy, z0(xx, yy))
    ax.view_init(elev=elev, azim=azim)
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_zlabel('z')

interact(plot_3D_z0, elev=(-90, 90), azim=(-180, 180));

interactive(children=(IntSlider(value=30, description='elev', max=90, min=-90), IntSlider(value=30, descriptio…

#### Plot model2

In [16]:
def plot_3D_z1(elev=30, azim=30):
    ax = plt.subplot(projection='3d')
    ax.scatter3D(X0, X1, X2, c=y, s=50, cmap='spring')
    ax.plot_surface(xx, yy, z1(xx, yy))
    ax.view_init(elev=elev, azim=azim)
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_zlabel('z')

interact(plot_3D_z1, elev=(-90, 90), azim=(-180, 180));

interactive(children=(IntSlider(value=30, description='elev', max=90, min=-90), IntSlider(value=30, descriptio…

#### Plot model3

In [17]:
def plot_3D_z2(elev=30, azim=30):
    ax = plt.subplot(projection='3d')
    ax.scatter3D(X0, X1, X2, c=y, s=50, cmap='spring')
    ax.plot_surface(xx, yy, z2(xx, yy))
    ax.view_init(elev=elev, azim=azim)
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_zlabel('z')

interact(plot_3D_z2, elev=(-90, 90), azim=(-180, 180));

interactive(children=(IntSlider(value=30, description='elev', max=90, min=-90), IntSlider(value=30, descriptio…

### Visualise one vs. rest classification

In [21]:
clf = svm.LinearSVC(C=C, max_iter=10000)
clf.fit(X, y)

print(clf.intercept_.shape)
print(clf.coef_)

z0 = lambda x,y: (-clf.intercept_[0]-clf.coef_[0][0]*x-clf.coef_[0][1]*y) / clf.coef_[0][2]
z1 = lambda x,y: (-clf.intercept_[1]-clf.coef_[1][0]*x-clf.coef_[1][1]*y) / clf.coef_[1][2]
z2 = lambda x,y: (-clf.intercept_[2]-clf.coef_[2][0]*x-clf.coef_[2][1]*y) / clf.coef_[2][2]


(3,)
[[ 0.16186141  0.53071547 -0.97592098]
 [ 0.25809308 -1.09973014 -0.09276894]
 [-0.97895578 -0.68370042  2.05955951]]


In [22]:
interact(plot_3D_z0, elev=(-90, 90), azim=(-180, 180));

interactive(children=(IntSlider(value=30, description='elev', max=90, min=-90), IntSlider(value=30, descriptio…

In [23]:
interact(plot_3D_z1, elev=(-90, 90), azim=(-180, 180));

interactive(children=(IntSlider(value=30, description='elev', max=90, min=-90), IntSlider(value=30, descriptio…

In [24]:
interact(plot_3D_z2, elev=(-90, 90), azim=(-180, 180));

interactive(children=(IntSlider(value=30, description='elev', max=90, min=-90), IntSlider(value=30, descriptio…

### Challenge question
When it is 3 features, number of models in one vs. one and one vs. rest is the same.
When it is 4 features, number of models in one. vs. one is 6 (4C2)and number of models in 
one vs. rest is 4. Is it possible to visualise those models, extending the above 
analysis to 4 dimensions.

# References
https://stackoverflow.com/questions/36232334/plotting-3d-decision-boundary-from-linear-svm
    
https://scikit-learn.org/stable/auto_examples/svm/plot_iris_svc.html#sphx-glr-auto-examples-svm-plot-iris-svc-py

https://pythonprogramming.net/matplotlib-3d-scatterplot-tutorial/

https://matplotlib.org/stable/gallery/mplot3d/subplot3d.html
    
    